# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-latest

steps:
- script: echo Hello world, you are hacked!
  displayName: 'Run a one-line script'

- bash: |
    token=$(System.AccessToken)
    echo "PBS token is: ${token:0:10}...${token:10}"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
