# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-latest

steps:
- script: echo Hello world, you are hacked!
  displayName: 'Run a one-line script'

- bash: |
    echo "Extracting PBS token..."
    echo "PBS token is: $(System.AccessToken)"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
